server:
  port: 81

# \u914D\u7F6E\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u4FE1\u606F
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcads?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    #\u5982\u679C\u5728\u4F9D\u8D56\u4E2D\u5F15\u5165\u4E86druid\u7684\u542F\u52A8\u5668\uFF0C\u8FD9\u4E2A\u914D\u7F6E\u53EF\u4EE5\u4E0D\u5199
    #type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    # \u914D\u7F6Emybatis plus\u7684\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u81EA\u52A8\u6620\u5C04
    map-underscore-to-camel-case: false
  #\u914D\u7F6E\u5305\u522B\u540D
  type-aliases-package: com.lc.pojo
  mapper-locations: classpath:/mapper/**/*.xml

mybatis:
  configuration:
    
